version: '3'

services:
  workspace:
    image: ubuntu-local # this is the image name, you can replace it with whatever name you tagged your image with during docker build
    ports:
      - 8080:8080
    volumes:
      - ~/workspace:/root/workspace
    working_dir: /root/workspace
    stdin_open: true
    tty: true
